### ISSUE TITLE
how to use jet algo rs256

### ISSUE THREAD

**Issue by gzanthony** [QThans/jwt-auth#9]
i create private & publi keys by follow setps:
1.openssl genrsa -out private.key 1024
2.openssl rsa -in private.key -pubout -out public.key

and then edit .env file add this follow lines:
[JWT]
ALGO=RS256
TTL=604820
PUBLIC_KEY=/data/cfdvq/runtime/public.key
PRIVATE_KEY=/data/cfdvq/runtime/private.key

but on execute, then will throw exceptions:

It was not possible to parse your key, reason: error:0909006C:PEM routines:get_name:no start line

 * Raises an exception when the key type is not the expected type
     *
     * @param resource|bool $key
     *
     * @throws InvalidArgumentException
     */
    private function validateKey($key)
    {
        if (! is_resource($key)) {
            throw new InvalidArgumentException(
                'It was not possible to parse your key, reason: ' . openssl_error_string()
            );
        }

        $details = openssl_pkey_get_details($key);

        if (! isset($details['key']) || $details['type'] !== $this->getKeyType()) {
            throw new InvalidArgumentException('This key is not compatible with this signer');
        }

it's my create keys steps error or someing else??

**Comment by QThans** [comment]
hi,
I'm sorry to reply now.
The work is too busy recently
I also met this error, but I'm afraid I can't solve it. It should be caused by the format. However, you can use text directly.like this:

![image](https://user-images.githubusercontent.com/18275400/72661597-f148e800-3a16-11ea-9a7e-7cd1e6e54873.png)

Thank you for using this composer
